name: SBOM Generator

on:
  push:
    branches:
      - main
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: spdx-json
          output-file: gujarati-python-sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: gujarati-python-sbom.spdx.json
